services:
  db:
    image: postgres:14-alpine
    container_name: db
    profiles:
      - dev
      - prod
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  db-admin:
    image: dpage/pgadmin4
    container_name: db-admin
    profiles:
      - dev
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin.servers.json:/data/pgadmin.servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_SERVER_JSON_FILE=//data/pgadmin.servers.json
volumes:
  db: